name: CI/CD

on:
  push:
    branches:
      - develop
  pull_request:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  test-and-publish:
    name: Test and publish
    uses: significa/actions/.github/workflows/vercel-app.yaml@main
    permissions:
      contents: read
      packages: write
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
